# Generated by Django 4.0.3 on 2022-03-24 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='module',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('module_ID', models.CharField(max_length=50, verbose_name='module_ID')),
                ('module_Name', models.CharField(max_length=50, verbose_name='module_Name')),
                ('Year', models.IntegerField(verbose_name='Year')),
                ('Semester', models.IntegerField(verbose_name='Semester')),
            ],
        ),
        migrations.CreateModel(
            name='professors',
            fields=[
                ('pro_ID', models.CharField(default='HYQ', max_length=50, primary_key=True, serialize=False, verbose_name='pro_ID')),
                ('pro_Name', models.CharField(max_length=50, verbose_name='pro_Name')),
            ],
        ),
        migrations.CreateModel(
            name='module_pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='score')),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sc18y2h.module', verbose_name='ID')),
                ('pro_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sc18y2h.professors', verbose_name='pro_Name')),
            ],
        ),
    ]
